var LESSONS={
1:[
 {id:"1-1",title:"How the body is organized — and why homeostasis is the whole point",mins:9,dia:"feedback",
  cards:["m1-1","m1-2","m1-3","m1-4","m1-5","m1-6","m1-7","m1-8","m1-17","d-feedback-stimulus","d-feedback-receptor","d-feedback-control","d-feedback-effector","d-feedback-response"],
  sections:[
   {h:"Six levels, one organism",p:"Anatomy is the study of <b>structure</b>; physiology is the study of <b>function</b>. They are inseparable — a structure exists because of what it does. The body is organized in nested levels: chemicals (atoms and molecules) build <b>cells</b>, cells with a shared job form <b>tissues</b>, tissues combine into <b>organs</b>, organs cooperate as <b>organ systems</b>, and eleven systems make the <b>organism</b>. When you meet any new structure in this course, place it on that ladder — it will tell you what to expect from it."},
   {h:"Homeostasis: the single idea every system serves",p:"Homeostasis is the maintenance of a relatively stable internal environment despite constant change outside and inside the body. Core temperature, blood pH, blood glucose, blood pressure, and fluid volume all sit inside narrow ranges. Every organ system you will study exists to defend one or more of those variables. This is the lens for the entire course: when you learn a new organ, ask <i>what variable is this protecting, and how does it know when to act?</i>"},
   {h:"Negative feedback — the mechanism of stability",p:"Almost all homeostatic control uses <b>negative feedback</b>: a change in a variable triggers a response that <i>reverses</i> the change. The loop has five parts. A <b>stimulus</b> pushes the variable off its set point. A <b>receptor</b> (sensor) detects it and reports to a <b>control center</b> — usually the brain or an endocrine gland — which compares the reading to the set point and sends a command to an <b>effector</b> (a muscle or gland). The effector's <b>response</b> opposes the original change, and once the variable is back in range the stimulus disappears and the loop quiets. Body temperature is the classic example: overheat → skin thermoreceptors → hypothalamus → sweat glands and dilated skin vessels → heat loss → temperature falls."},
   {h:"Positive feedback — rare, and always meant to finish",p:"Positive feedback <i>amplifies</i> a change instead of reversing it, so it is only used when the body wants a process to accelerate to completion. Childbirth is the textbook case: uterine contractions push the baby against the cervix, stretch receptors signal the brain, oxytocin is released, contractions get stronger, and the cycle escalates until delivery ends it. Blood clotting works the same way — activated platelets recruit more platelets until the plug is sealed."},
   {h:"Speaking anatomy: position and direction",p:"All directional language assumes <b>anatomical position</b>: standing erect, face forward, arms at the sides, palms forward. From there, <b>superior/inferior</b> mean toward the head or feet; <b>anterior/posterior</b> mean toward the front or back; <b>medial/lateral</b> mean toward or away from the midline; <b>proximal/distal</b> mean closer to or farther from the trunk (used for limbs); <b>superficial/deep</b> mean toward or away from the surface. The body's two major cavities are the <b>dorsal</b> cavity (cranial and spinal) and the <b>ventral</b> cavity (thoracic and abdominopelvic). Learn these once and every description in the book, and every chart note in your career, becomes readable."}
  ],
  terms:[["Homeostasis","Maintenance of a stable internal environment within narrow limits."],["Set point","The target value a control system defends."],["Negative feedback","A response that reverses the original change."],["Effector","The muscle or gland that carries out the response."],["Anatomical position","Erect, facing forward, palms forward — the reference for all directional terms."]],
  clinical:"Vital signs are homeostasis made visible. Temperature, pulse, respirations, blood pressure, and oxygen saturation are the body's defended variables read from the outside. When a patient's vitals drift, you are watching a feedback loop struggle — and the questions in this lesson (what is the stimulus, what is the effector, is it compensating?) are exactly the questions a nurse asks at the bedside."},
 {id:"1-2",title:"The chemistry you cannot skip — water, pH, and the four biomolecules",mins:9,dia:null,
  cards:["m1-9","m1-10","m1-11","m1-12","m1-13","m1-14","m1-15","m1-16"],
  sections:[
   {h:"Atoms, ions, and why electrolytes matter",p:"Four elements — oxygen, carbon, hydrogen, and nitrogen — make up about 96% of body mass. Atoms bond in two main ways. <b>Ionic bonds</b> transfer electrons, leaving charged particles called <b>ions</b>; when a compound like NaCl dissolves, it separates into Na⁺ and Cl⁻. Substances that dissociate into ions in water are <b>electrolytes</b>, and because they carry charge they conduct electrical signals — which is why sodium, potassium, and calcium levels govern how nerves fire and muscles contract. <b>Covalent bonds</b> share electrons and hold the stable backbones of biological molecules together."},
   {h:"Water: the medium everything happens in",p:"Water is polar — its oxygen end is slightly negative and its hydrogen ends slightly positive — so it surrounds and dissolves other polar and charged substances. That makes it the <b>universal solvent</b> and the reason blood can carry salts, sugars, and proteins. Water also has a high heat capacity, buffering temperature changes, and it participates directly in reactions (hydrolysis breaks bonds by adding water; dehydration synthesis builds them by removing it). Roughly 60% of adult body weight is water, and about two-thirds of it is inside cells."},
   {h:"pH and buffers: the narrowest window in the body",p:"pH measures hydrogen ion concentration on a scale of 0–14; below 7 is acidic, above 7 is basic. Arterial blood is held between <b>7.35 and 7.45</b> — slightly alkaline, and that range is defended more aggressively than almost any other variable, because enzymes and hemoglobin change shape outside it. Below 7.35 is <b>acidosis</b>; above 7.45 is <b>alkalosis</b>. <b>Buffers</b> resist pH change by accepting or releasing H⁺ as needed; the bicarbonate buffer (HCO₃⁻ / H₂CO₃) is the body's most important one and links directly to the lungs (which control CO₂) and the kidneys (which control bicarbonate). You will meet this again as the entire basis of acid–base balance in Module 8."},
   {h:"The four biomolecules and their jobs",p:"<b>Carbohydrates</b> (sugars and starches) are quick fuel; glucose is the body's preferred energy source and is stored as glycogen. <b>Lipids</b> (fats, phospholipids, steroids) store energy densely, build every cell membrane, insulate, and serve as the raw material for steroid hormones like cortisol and estrogen. <b>Proteins</b> are chains of amino acids folded into precise shapes; they provide structure (collagen, keratin), act as enzymes, carry molecules (hemoglobin), and defend the body (antibodies). <b>Nucleic acids</b> (DNA, RNA) store and transmit genetic information. <b>ATP</b> — adenosine triphosphate — is the cell's immediate energy currency; nearly every process that costs energy, from a muscle twitch to an ion pump, spends ATP."},
   {h:"Metabolism in one sentence",p:"Metabolism is the sum of all chemical reactions in the body, split into <b>catabolism</b> (breaking molecules down and releasing energy, like burning glucose) and <b>anabolism</b> (building molecules and consuming energy, like assembling proteins). Enzymes make these reactions possible at body temperature by lowering the energy required — and because enzymes are proteins, they are the first casualties of a pH or temperature outside the normal range."}
  ],
  terms:[["Electrolyte","A substance that separates into ions in water and conducts electricity."],["Buffer","A chemical system that resists changes in pH."],["Acidosis","Blood pH below 7.35."],["ATP","The cell's immediate energy currency."],["Catabolism","Reactions that break molecules down and release energy."]],
  clinical:"Nearly every lab panel you will ever read is this lesson. A basic metabolic panel reports electrolytes (Na⁺, K⁺, Cl⁻, HCO₃⁻) and glucose; an arterial blood gas reports pH, CO₂, and bicarbonate. A potassium of 6.0 can stop a heart; a pH of 7.2 can shut down enzymes body-wide. Chemistry is not background here — it is the patient."}
],
2:[
 {id:"2-1",title:"The cell membrane and how things get across it",mins:8,dia:null,
  cards:["m2-1","m2-2","m2-3","m2-4","m2-5","m2-6","m2-7","m2-8","m2-9"],
  sections:[
   {h:"A bilayer with gates",p:"The plasma membrane is a <b>phospholipid bilayer</b>: two layers of molecules with water-loving heads facing outward toward the fluid on each side and water-fearing tails tucked inward. This makes it <b>selectively permeable</b> — small lipid-soluble substances like oxygen, carbon dioxide, and steroid hormones slip straight through, while water-soluble and charged particles (ions, glucose, amino acids) cannot cross without help. Embedded proteins provide that help as channels, carriers, and pumps; cholesterol stiffens the membrane; carbohydrate tags on the outer surface serve as identity markers the immune system reads."},
   {h:"Passive transport: free, downhill",p:"Passive transport moves substances <i>down</i> their concentration gradient — from high to low — and costs no ATP. <b>Simple diffusion</b> is a lipid-soluble molecule drifting straight through the bilayer. <b>Facilitated diffusion</b> uses a channel or carrier protein for a substance that cannot cross on its own, still downhill, still free — glucose enters most cells this way. <b>Osmosis</b> is the diffusion of <i>water</i> across a selectively permeable membrane toward the side with more solute. <b>Filtration</b> pushes fluid through a membrane by pressure, which is exactly how the kidney begins making urine."},
   {h:"Active transport: pumps that spend ATP",p:"When a cell needs to move something <i>against</i> its gradient, it pays. The most important pump in the body is the <b>sodium–potassium pump</b> (Na⁺/K⁺-ATPase), which pushes three Na⁺ out and pulls two K⁺ in for every ATP spent. That single pump maintains the gradients — sodium high outside, potassium high inside — that every nerve impulse and muscle contraction depends on, and it consumes a substantial share of the body's resting energy. Cells also move bulk material with vesicles: <b>endocytosis</b> brings things in, <b>exocytosis</b> sends things out."},
   {h:"Tonicity: what happens to a cell in a solution",p:"Tonicity describes how a solution affects a cell's water balance. In an <b>isotonic</b> solution the solute concentration matches the cell, so there is no net water movement — 0.9% normal saline is isotonic, which is why it can be infused into a vein safely. In a <b>hypotonic</b> solution (less solute outside), water rushes in and the cell swells and may burst. In a <b>hypertonic</b> solution (more solute outside), water is drawn out and the cell shrinks. Red blood cells demonstrate all three dramatically under a microscope."}
  ],
  terms:[["Selectively permeable","Lets some substances cross and blocks others."],["Osmosis","Diffusion of water toward the higher solute concentration."],["Na⁺/K⁺ pump","Active transporter: 3 Na⁺ out, 2 K⁺ in, per ATP."],["Isotonic","Same solute concentration as the cell; no net water shift."],["Hypertonic","Higher solute outside the cell; the cell shrinks."]],
  clinical:"IV fluid therapy is applied tonicity. Normal saline and lactated Ringer's are isotonic and expand blood volume without shifting water into or out of cells. Half-normal saline is hypotonic and pushes water into cells — useful for dehydration, dangerous for a swelling brain. Hypertonic saline pulls water out of swollen tissue. Choosing the wrong bag is a cell-membrane error with a patient attached."},
 {id:"2-2",title:"Inside the cell — the organelles and what each one is for",mins:8,dia:"cell",
  cards:["m2-10","m2-11","m2-12","m2-13","m2-14","m2-20","d-cell-membrane","d-cell-nucleus","d-cell-mito","d-cell-er","d-cell-golgi"],
  sections:[
   {h:"The nucleus runs the show",p:"The <b>nucleus</b> holds the cell's DNA and directs everything the cell does by controlling which proteins get made. Inside it, the <b>nucleolus</b> assembles ribosomes. The nuclear envelope is a double membrane with pores that let messenger RNA out and regulatory proteins in. Almost every cell has one nucleus; mature red blood cells eject theirs to make room for hemoglobin, and skeletal muscle fibers carry many."},
   {h:"Making protein: ribosomes, ER, and Golgi",p:"Protein synthesis is an assembly line. <b>Ribosomes</b> read messenger RNA and string amino acids together. Ribosomes studding the <b>rough endoplasmic reticulum</b> make proteins destined for membranes or for export; the ER folds and checks them. <b>Smooth ER</b> has no ribosomes and instead makes lipids, stores calcium (critically, in muscle), and detoxifies drugs — liver cells are packed with it. Finished proteins travel in vesicles to the <b>Golgi apparatus</b>, which modifies, sorts, and packages them for delivery inside the cell or secretion outside it."},
   {h:"Power and cleanup",p:"<b>Mitochondria</b> convert glucose and oxygen into ATP through cellular respiration; cells with heavy energy demands — heart muscle, kidney tubule cells — are crowded with them. <b>Lysosomes</b> are membrane-bound bags of digestive enzymes that dismantle worn-out organelles, debris, and engulfed bacteria. <b>Peroxisomes</b> neutralize toxic peroxides. The <b>cytoskeleton</b> — microfilaments, intermediate filaments, and microtubules — gives the cell its shape, moves organelles around, and forms the spindle during cell division."},
   {h:"Dividing: the cell cycle",p:"Somatic cells reproduce by <b>mitosis</b>, producing two genetically identical daughter cells. The cycle runs through interphase (growth and DNA replication), then the stages of mitosis — <b>prophase, metaphase, anaphase, telophase</b> — followed by cytokinesis, when the cytoplasm splits. Tissues that renew constantly (skin, gut lining, bone marrow) divide rapidly; nervous and cardiac muscle cells largely do not, which is why their injuries heal poorly."}
  ],
  terms:[["Mitochondrion","Site of ATP production."],["Rough ER","Ribosome-studded; makes and folds proteins."],["Golgi apparatus","Modifies, sorts, and packages proteins."],["Lysosome","Digestive enzyme sac for cellular cleanup."],["Mitosis","Division producing two identical cells."]],
  clinical:"Chemotherapy targets the cell cycle: it kills rapidly dividing cells, which is why it hits cancer — and also hair follicles, the gut lining, and bone marrow, producing the classic side effects of hair loss, nausea, and low blood counts. Understanding which tissues divide fast predicts which will be harmed."},
 {id:"2-3",title:"The four tissue types — the vocabulary of every organ",mins:8,dia:null,
  cards:["m2-15","m2-16","m2-17","m2-18","m2-19"],
  sections:[
   {h:"Only four, and every organ is a mix",p:"Every organ in the body is built from just four tissue types: <b>epithelial</b>, <b>connective</b>, <b>muscle</b>, and <b>nervous</b>. The stomach, for example, has an epithelial lining, connective tissue support and blood supply, muscle in its wall, and nerves that coordinate it. Recognizing tissue types is what makes microscope work — and pathology reports — readable."},
   {h:"Epithelial tissue: covering and lining",p:"Epithelium covers the body surface and lines every cavity, tube, and gland. Its cells are tightly packed with almost no space between them, sit on a <b>basement membrane</b>, and are <b>avascular</b> — they have no blood vessels of their own and are fed by diffusion from the connective tissue beneath. It is classified by shape (squamous, cuboidal, columnar) and layering (simple or stratified): simple squamous epithelium is one cell thick for rapid exchange in alveoli and capillaries; stratified squamous epithelium is many layers thick for protection in skin and the esophagus. Epithelium regenerates quickly, which is why surface wounds heal fast."},
   {h:"Connective tissue: the most abundant and most varied",p:"Connective tissue binds, supports, protects, and transports. What defines it is an abundant <b>extracellular matrix</b> — cells scattered in ground substance and protein fibers (collagen for strength, elastin for stretch, reticular fibers for scaffolding). That broad definition includes loose and dense connective tissue, <b>adipose</b> (fat), <b>cartilage</b>, <b>bone</b>, and — because plasma is its matrix — <b>blood</b>. Tendons (muscle to bone) and ligaments (bone to bone) are dense regular connective tissue built from parallel collagen bundles."},
   {h:"Muscle and nervous tissue",p:"<b>Muscle tissue</b> contracts. Skeletal muscle is striated and voluntary; cardiac muscle is striated, involuntary, and joined by intercalated discs so the heart beats as one unit; smooth muscle is non-striated and involuntary, lining hollow organs and vessels. <b>Nervous tissue</b> consists of neurons, which generate and conduct electrical signals, and neuroglia, which support and protect them. Both muscle and nervous tissue have very limited ability to regenerate — damage tends to be replaced by scar rather than new function."}
  ],
  terms:[["Basement membrane","The layer anchoring epithelium to the connective tissue below."],["Avascular","Without its own blood supply."],["Extracellular matrix","The material connective-tissue cells sit in."],["Intercalated disc","Junction coupling cardiac muscle cells electrically."],["Tendon vs. ligament","Tendon: muscle to bone. Ligament: bone to bone."]],
  clinical:"Wound healing is a tissue story. A superficial scrape re-epithelializes in days because epithelium regenerates. A deep laceration through the dermis heals by connective-tissue scar. A myocardial infarction kills cardiac muscle that cannot regenerate, so the heart is left with a stiff patch of scar — which is why the damage is permanent and why the rhythm around it becomes unstable."}
]
};
LESSONS[3]=[
 {id:"3-1",title:"Skin — three layers, and what each one does for you",mins:9,dia:"skin",
  cards:["m3-1","m3-2","m3-3","m3-4","m3-5","m3-6","d-skin-epi","d-skin-derm","d-skin-hypo","d-skin-foll","d-skin-sweat"],
  sections:[
   {h:"The largest organ, and a real one",p:"Skin is not a wrapper — it is an organ with measurable jobs: physical and chemical <b>protection</b>, <b>thermoregulation</b>, <b>sensation</b>, <b>vitamin D synthesis</b> when sunlight hits it, and <b>prevention of fluid loss</b>. It accounts for roughly 15% of body weight. When a large area is destroyed, as in a major burn, the patient dies of what the skin was quietly doing: fluid loss, heat loss, and infection."},
   {h:"Epidermis: the barrier",p:"The <b>epidermis</b> is the outer layer — stratified squamous epithelium, and therefore <b>avascular</b>; it is fed by diffusion from below. New cells are born in the deepest layer (stratum basale) and pushed upward over about a month, filling with the tough protein <b>keratin</b> and dying by the time they reach the surface, where they flake off. <b>Melanocytes</b> in the basal layer produce <b>melanin</b>, which gives skin its color and absorbs UV radiation to protect the DNA of the cells beneath. Thick skin on palms and soles has five layers; thin skin elsewhere has four."},
   {h:"Dermis: the living layer",p:"The <b>dermis</b> is dense irregular connective tissue and holds everything that makes skin alive: <b>blood vessels</b>, <b>nerve endings</b> and touch receptors, <b>hair follicles</b>, <b>sebaceous (oil) glands</b>, and <b>sweat glands</b>. Its upper papillary layer projects upward into the epidermis as <b>dermal papillae</b>, interlocking the two layers so they do not shear apart (and producing your fingerprints). The deeper reticular layer's collagen and elastin give skin its strength and stretch; when they are damaged by age or sun, skin sags and wrinkles."},
   {h:"Hypodermis and the accessory structures",p:"Below the dermis lies the <b>hypodermis</b> (subcutaneous layer) — loose connective and <b>adipose</b> tissue that insulates, cushions, stores energy, and anchors skin to underlying muscle. It is technically not skin, but it is where subcutaneous injections go. Among the accessory structures, <b>eccrine sweat glands</b> cover most of the body and cool it by evaporation; <b>apocrine</b> glands in the axilla and groin activate at puberty; <b>sebaceous glands</b> secrete oily sebum into hair follicles to waterproof and lubricate; and each <b>hair follicle</b> is a tube of epidermis reaching down into the dermis, with a bulb at its base where the hair grows and a tiny arrector pili muscle that stands it upright — goosebumps."},
   {h:"How skin controls temperature",p:"When core temperature rises, the hypothalamus dilates dermal blood vessels — bringing warm blood to the surface to radiate heat — and activates sweat glands so evaporation carries heat away. When core temperature drops, vessels constrict to keep blood deep, and shivering generates heat. This is negative feedback from Module 1, with skin as the effector."}
  ],
  terms:[["Keratin","Tough protein that makes the epidermis durable and waterproof."],["Melanin","Pigment that colors skin and absorbs UV."],["Dermal papillae","Upward projections interlocking dermis with epidermis."],["Sebaceous gland","Secretes sebum into hair follicles."],["Eccrine gland","Sweat gland for evaporative cooling."]],
  clinical:"Burn depth is skin anatomy. A superficial (first-degree) burn involves only the epidermis — red, painful, heals without scarring. A partial-thickness (second-degree) burn reaches into the dermis — blisters, because fluid collects between the layers. A full-thickness (third-degree) burn destroys the dermis and its nerve endings — often painless in the center, and it cannot regenerate, so it needs grafting. Pressure injuries follow the same layers, from intact reddened skin down to exposed bone."},
 {id:"3-2",title:"Bone as living tissue — cells, remodeling, and the calcium bank",mins:8,dia:null,
  cards:["m3-10","m3-11","m3-12","m3-13","m3-20"],
  sections:[
   {h:"Bone is alive and busy",p:"Bone is dense connective tissue whose matrix is hardened by calcium phosphate crystals laid down on a collagen framework — collagen for flexibility, mineral for hardness. It is not inert. It is constantly being torn down and rebuilt by three cell types: <b>osteoblasts</b> build new bone matrix, <b>osteocytes</b> are mature osteoblasts trapped in the matrix that maintain it and sense stress, and <b>osteoclasts</b> dissolve bone and release its minerals into the blood. Roughly 10% of your skeleton is replaced every year."},
   {h:"Compact and spongy bone",p:"<b>Compact bone</b> is the dense outer shell, organized into cylindrical units called osteons around central canals that carry blood vessels. <b>Spongy (cancellous) bone</b> inside is a lattice of struts called trabeculae, arranged along lines of stress; it is lighter and its spaces hold <b>red bone marrow</b>, where blood cells are made. A long bone has a shaft (diaphysis) of compact bone around a marrow cavity, and expanded ends (epiphyses) of spongy bone capped with articular cartilage."},
   {h:"Remodeling responds to load and hormones",p:"Bone remodels in response to mechanical stress: weight-bearing exercise stimulates osteoblasts and thickens bone, while bed rest or weightlessness lets osteoclasts win and bone thins. Hormones tune the balance. <b>Parathyroid hormone</b> raises blood calcium by stimulating osteoclasts; <b>calcitonin</b> lowers it by inhibiting them. Estrogen and testosterone restrain osteoclasts, which is why bone density falls after menopause. Vitamin D is required to absorb calcium from the gut at all."},
   {h:"The skeleton as the calcium bank",p:"About 99% of the body's calcium is stored in bone. Blood calcium must stay within a narrow range because calcium drives muscle contraction, nerve signaling, and blood clotting — so when dietary calcium falls short, the body withdraws from bone to keep the blood level steady. Long-term withdrawals weaken the skeleton; this is the physiological root of <b>osteoporosis</b>, in which osteoclast resorption outpaces osteoblast formation and bones become porous and fracture-prone."}
  ],
  terms:[["Osteoblast","Bone-building cell."],["Osteoclast","Bone-resorbing cell."],["Osteocyte","Mature bone cell maintaining the matrix."],["Trabeculae","The struts of spongy bone."],["Osteoporosis","Loss of bone density from resorption exceeding formation."]],
  clinical:"A hip fracture in an older adult is usually osteoporosis catching up. Nursing care follows the physiology: weight-bearing as early as safely possible (load stimulates osteoblasts), adequate calcium and vitamin D, and awareness that immobility itself accelerates bone loss. Serum calcium is also on every basic panel — and a high value can mean the parathyroids or a tumor are pulling calcium out of bone."},
 {id:"3-3",title:"The skeleton and its joints — axial, appendicular, and how bones move",mins:9,dia:"skeleton",
  cards:["m3-7","m3-8","m3-9","m3-14","m3-15","m3-16","m3-17","m3-18","m3-19","d-skeleton-skull","d-skeleton-clavicle","d-skeleton-ribs","d-skeleton-spine","d-skeleton-humerus","d-skeleton-forearm","d-skeleton-pelvis","d-skeleton-femur","d-skeleton-tibfib"],
  sections:[
   {h:"206 bones in two divisions",p:"The adult skeleton has 206 bones split into two divisions. The <b>axial skeleton</b> forms the body's central axis: the <b>skull</b> (22 bones including the mandible), the <b>vertebral column</b>, and the <b>thoracic cage</b> (12 pairs of ribs and the sternum). The <b>appendicular skeleton</b> is everything that hangs off it: the <b>pectoral girdle</b> (clavicle and scapula), the upper limbs, the <b>pelvic girdle</b> (hip bones), and the lower limbs. The skeleton supports the body, protects organs, provides levers for muscles, stores minerals, and houses the marrow that makes blood."},
   {h:"The vertebral column",p:"Thirty-three vertebrae are stacked in five regions: <b>7 cervical</b> (neck), <b>12 thoracic</b> (each articulates with a rib), <b>5 lumbar</b> (the largest, bearing the most weight), then the <b>sacrum</b> (5 fused) and <b>coccyx</b> (4 fused). Intervertebral discs of fibrocartilage cushion the movable vertebrae. The column protects the spinal cord, which runs through the vertebral foramina and ends around L1–L2 — which is why a lumbar puncture is done below that level."},
   {h:"The limbs, bone by bone",p:"Upper limb: <b>humerus</b> (upper arm), then <b>radius</b> on the thumb side and <b>ulna</b> on the pinky side, then 8 carpals, 5 metacarpals, and 14 phalanges. Lower limb: <b>femur</b> (the longest and strongest bone in the body), the <b>patella</b>, then the weight-bearing <b>tibia</b> medially and the slender <b>fibula</b> laterally, then 7 tarsals, 5 metatarsals, and 14 phalanges. The <b>clavicle</b> is the most commonly fractured bone; the femoral neck is the classic osteoporotic fracture site."},
   {h:"Joints: classified by how much they move",p:"A joint (articulation) is anywhere two bones meet. By function: <b>synarthroses</b> are immovable (skull sutures), <b>amphiarthroses</b> slightly movable (intervertebral discs, pubic symphysis), and <b>diarthroses</b> freely movable. All freely movable joints are <b>synovial joints</b>: the bone ends are covered with articular cartilage, enclosed in a fibrous capsule, and lubricated by synovial fluid. <b>Ligaments</b> connect bone to bone and stabilize the joint; <b>tendons</b> connect muscle to bone and move it. Movements are named in pairs — flexion/extension, abduction/adduction, rotation, pronation/supination — and you will use those words in every assessment."}
  ],
  terms:[["Axial skeleton","Skull, vertebral column, thoracic cage."],["Appendicular skeleton","Limbs plus the girdles that attach them."],["Synovial joint","Freely movable joint with a fluid-filled cavity."],["Ligament","Connects bone to bone."],["Pronation / supination","Turning the palm down / up."]],
  clinical:"Range-of-motion assessment is joint anatomy in action, and fall risk is skeleton anatomy: the femoral neck, the distal radius (a fall onto an outstretched hand), and the vertebral bodies are where osteoporotic bones break. Knowing that the spinal cord ends near L1–L2 is why a lumbar puncture is safe at L3–L4 and why a thoracic spine injury threatens breathing but a low lumbar one does not."}
];
LESSONS[4]=[
 {id:"4-1",title:"How a muscle contracts — from nerve impulse to sliding filaments",mins:10,dia:"sarcomere",
  cards:["m4-1","m4-2","m4-3","m4-4","m4-5","m4-6","m4-7","m4-8","m4-9","m4-10","d-sarcomere-z","d-sarcomere-actin","d-sarcomere-myosin","d-sarcomere-sarco"],
  sections:[
   {h:"Three kinds of muscle",p:"<b>Skeletal muscle</b> is striated, voluntary, and attached to bone. <b>Cardiac muscle</b> is striated and involuntary, its cells joined end to end by <b>intercalated discs</b> that pass the electrical signal cell to cell so the heart contracts as a unit. <b>Smooth muscle</b> is non-striated and involuntary, wrapping hollow organs and blood vessels. All three share the same basic mechanism of contraction; this lesson uses skeletal muscle to teach it."},
   {h:"The sarcomere and the sliding filament model",p:"A muscle fiber is packed with myofibrils, each a chain of repeating units called <b>sarcomeres</b> running from one <b>Z-disc</b> to the next. Inside each sarcomere, thin filaments of <b>actin</b> anchor to the Z-discs and thick filaments of <b>myosin</b> sit in the center. Contraction happens when myosin heads grab the actin and pull it toward the middle: the Z-discs draw closer, the sarcomere shortens, and thousands of sarcomeres shortening together shorten the muscle. This is the <b>sliding filament model</b> — the filaments <i>slide past</i> each other; neither one gets shorter. The striations you see under a microscope are the overlapping bands of these filaments."},
   {h:"Calcium is the switch",p:"At rest, the binding sites on actin are covered by a strand of <b>tropomyosin</b> held in place by <b>troponin</b>. Contraction begins when <b>calcium</b> floods the cytoplasm and binds troponin, which shifts tropomyosin aside and exposes the sites. Now myosin heads can attach, forming <b>cross-bridges</b>. When calcium is pumped back into storage, tropomyosin covers the sites again and the muscle relaxes. No calcium, no contraction — every step downstream depends on this."},
   {h:"From nerve to fiber: excitation–contraction coupling",p:"A motor neuron delivers the command at the <b>neuromuscular junction</b>. The neuron releases <b>acetylcholine (ACh)</b>, which binds receptors on the muscle fiber and triggers an electrical impulse that races along the fiber's membrane and down into it through T-tubules. That impulse causes the <b>sarcoplasmic reticulum</b> — the fiber's calcium store — to release calcium, and the sliding filament cycle begins. The enzyme acetylcholinesterase then breaks down ACh so the signal stops; drugs and toxins that block this enzyme cause sustained contraction."},
   {h:"ATP does double duty",p:"ATP powers the myosin power stroke — but it also has a second job: a fresh ATP must bind the myosin head to <i>release</i> it from actin so the cycle can repeat. Without ATP, myosin stays locked to actin. This is exactly what happens after death: ATP production stops, cross-bridges cannot detach, and the muscles stiffen into <b>rigor mortis</b> until the proteins themselves degrade."}
  ],
  terms:[["Sarcomere","The contractile unit, Z-disc to Z-disc."],["Sliding filament model","Myosin pulls actin inward; filaments slide, not shorten."],["Troponin / tropomyosin","Regulatory proteins that hide actin's binding sites until calcium arrives."],["Neuromuscular junction","Where a motor neuron meets a muscle fiber; ACh is the messenger."],["Sarcoplasmic reticulum","The muscle fiber's calcium reservoir."]],
  clinical:"Two common drug classes act right here. Neuromuscular blockers used in surgery and intubation occupy the ACh receptor so the fiber cannot be triggered — the patient is paralyzed until it wears off or is reversed. Calcium's role also explains why severe hypocalcemia produces muscle spasms and tetany: low calcium makes nerve and muscle membranes hyperexcitable."},
 {id:"4-2",title:"Muscle in action — energy, fiber types, and how muscles work together",mins:8,dia:null,
  cards:["m4-11","m4-12","m4-13","m4-14","m4-15","m4-16","m4-17","m4-18"],
  sections:[
   {h:"Motor units and graded strength",p:"A <b>motor unit</b> is one motor neuron plus every muscle fiber it controls. Fine-control muscles (eyes, fingers) have small motor units of a few fibers; power muscles (thigh) have units of hundreds. The nervous system grades force by recruiting more motor units and by firing them faster: a single stimulus gives a <b>twitch</b>; rapid repeated stimuli fuse into a sustained, stronger contraction called <b>tetanus</b>. Even at rest, a few motor units are always active, producing <b>muscle tone</b> — the slight firmness that keeps posture without movement."},
   {h:"Fueling contraction",p:"Muscles keep only a few seconds of ATP on hand. Creatine phosphate donates a phosphate to regenerate ATP for about 15 seconds of all-out effort. Then <b>anaerobic glycolysis</b> takes over, producing ATP quickly without oxygen but generating <b>lactic acid</b> and lasting perhaps a minute. For anything longer, <b>aerobic respiration</b> in the mitochondria supplies ATP steadily as long as oxygen and fuel arrive. After intense exercise, the body keeps breathing hard to repay the <b>oxygen debt</b> — clearing lactate and restocking creatine phosphate."},
   {h:"Isotonic and isometric contraction",p:"An <b>isotonic</b> contraction changes the muscle's length and moves a load — lifting a cup. A contraction that shortens the muscle is concentric; one that lengthens it under load (lowering the cup) is eccentric. An <b>isometric</b> contraction develops tension without changing length — holding a plank, or pushing against a wall. Both kinds happen constantly during ordinary movement and posture."},
   {h:"Muscles work in pairs and are named for what they do",p:"Muscles only pull; they cannot push. So they work in opposing pairs: the <b>agonist</b> (prime mover) produces the action, the <b>antagonist</b> opposes or reverses it, and synergists assist. The biceps flexes the elbow while the triceps extends it. A muscle's fixed attachment is its <b>origin</b>; the attachment on the bone that moves is its <b>insertion</b>. Muscle names encode location, shape, size, action, or attachments — <i>rectus abdominis</i>, <i>biceps brachii</i>, <i>gluteus maximus</i> — so a name is usually a description once you know the roots. The <b>diaphragm</b>, the main muscle of breathing, is innervated by the phrenic nerve (C3–C5): a spinal cord injury above that level stops breathing."}
  ],
  terms:[["Motor unit","One motor neuron and all the fibers it innervates."],["Muscle tone","Continuous low-level contraction maintaining posture."],["Oxygen debt","Extra oxygen consumed after exercise to restore the muscle."],["Agonist / antagonist","Prime mover / the muscle that opposes it."],["Origin / insertion","Stationary attachment / moving attachment."]],
  clinical:"Intramuscular injection sites are chosen by anatomy: the deltoid, vastus lateralis, and ventrogluteal sites have thick muscle away from major nerves and vessels. Muscle tone is part of every neurological assessment — flaccid (absent tone) points to a lower motor neuron or spinal shock problem, spastic (increased tone) to an upper motor neuron lesion like stroke."}
];
LESSONS[5]=[
 {id:"5-1",title:"Nervous tissue and how the system is organized",mins:8,dia:"neuron",
  cards:["m5-1","m5-2","m5-3","m5-4","m5-10","m5-11","m5-12","m5-25","m5-28","d-neuron-dend","d-neuron-soma","d-neuron-axon","d-neuron-myelin","d-neuron-node","d-neuron-term"],
  sections:[
   {h:"Central and peripheral",p:"The nervous system has two structural divisions. The <b>central nervous system (CNS)</b> is the brain and spinal cord — the integration center. The <b>peripheral nervous system (PNS)</b> is every nerve outside it. Functionally, the PNS carries <b>sensory (afferent)</b> input toward the CNS and <b>motor (efferent)</b> output away from it. Motor output splits again into the <b>somatic</b> nervous system (voluntary control of skeletal muscle) and the <b>autonomic</b> nervous system (involuntary control of organs, vessels, and glands), which itself has sympathetic and parasympathetic branches — the subject of a later lesson."},
   {h:"The neuron",p:"The neuron is the signaling cell. <b>Dendrites</b> receive input and carry it toward the <b>cell body (soma)</b>, which holds the nucleus and integrates the signals. If the sum crosses threshold, an impulse launches down the <b>axon</b> — a single long fiber — to the <b>axon terminals</b>, which release chemical messengers onto the next cell at a <b>synapse</b>. Signals travel one direction: dendrites in, axon out. Neurons are among the longest-lived cells in the body and, in most of the CNS, do not divide to replace themselves."},
   {h:"Glia: the support crew",p:"Neurons are outnumbered by <b>neuroglia</b>, which do not fire but make firing possible. In the CNS, <b>astrocytes</b> regulate the chemical environment and help form the blood–brain barrier; <b>microglia</b> are immune cells; ependymal cells line the fluid-filled ventricles; and <b>oligodendrocytes</b> make myelin. In the PNS, <b>Schwann cells</b> make myelin and satellite cells support cell bodies. Most brain tumors arise from glia, not neurons — gliomas — because glia are the cells that still divide."},
   {h:"Myelin and speed",p:"<b>Myelin</b> is a fatty, insulating wrap laid down in segments along an axon, with tiny gaps called <b>nodes of Ranvier</b> between them. Because the insulated stretches cannot leak charge, the impulse jumps from node to node — <b>saltatory conduction</b> — up to fifty times faster than in an unmyelinated axon. Myelinated axons appear white, so <b>white matter</b> is mostly myelinated tracts (transmission) and <b>gray matter</b> is mostly cell bodies and unmyelinated fibers (processing). In <b>multiple sclerosis</b>, the immune system destroys CNS myelin; conduction slows or fails along the affected axons, producing the disease's shifting weakness, numbness, and vision problems."}
  ],
  terms:[["Afferent / efferent","Toward the CNS (sensory) / away from it (motor)."],["Dendrite","Receives signals and carries them to the cell body."],["Oligodendrocyte / Schwann cell","Myelin-makers in the CNS / PNS."],["Saltatory conduction","Impulse jumping node to node along a myelinated axon."],["Gray vs. white matter","Cell bodies (processing) vs. myelinated axons (transmission)."]],
  clinical:"Peripheral nerves can regenerate slowly along their Schwann-cell sheath, which is why a cut finger nerve may recover sensation over months. CNS axons essentially cannot, which is why spinal cord injury is permanent. Guillain-Barré syndrome demyelinates peripheral nerves and MS demyelinates central ones — same mechanism, opposite division, very different courses."},
 {id:"5-2",title:"Membrane potentials and the action potential",mins:10,dia:"actionpotential",
  cards:["m5-5","m5-6","m5-7","m5-8","m5-9","d-actionpotential-rest","d-actionpotential-thresh","d-actionpotential-depol","d-actionpotential-repol","d-actionpotential-hyper"],
  sections:[
   {h:"The resting neuron is a charged battery",p:"A resting neuron holds a voltage across its membrane of about <b>−70 mV</b> — the inside negative relative to the outside. Two things create it. The <b>sodium–potassium pump</b> keeps sodium concentrated outside and potassium concentrated inside. And the membrane at rest is far more permeable to K⁺ than to Na⁺, so potassium leaks out down its gradient, carrying positive charge away and leaving the interior negative. This <b>resting membrane potential</b> is stored energy, and it is why changes in blood potassium have such dramatic effects on nerve and heart."},
   {h:"Gated channels and threshold",p:"Neurons change their voltage by opening ion channels. Ligand-gated channels open when a neurotransmitter binds; mechanically gated channels open with stretch or pressure; <b>voltage-gated</b> channels open at a specific membrane voltage. A stimulus that lets a little Na⁺ in nudges the membrane toward zero — a small, local <b>graded potential</b>. If enough graded potentials sum to reach <b>threshold</b>, about <b>−55 mV</b>, the voltage-gated sodium channels fly open and an action potential fires. Below threshold, nothing happens; at threshold, it fires fully. This is the <b>all-or-none</b> principle: a stronger stimulus does not make a bigger impulse — it makes <i>more frequent</i> impulses."},
   {h:"The action potential, phase by phase",p:"<b>Depolarization</b>: voltage-gated Na⁺ channels open, sodium rushes in, and the membrane potential shoots up to about +30 mV. <b>Repolarization</b>: sodium channels inactivate, voltage-gated K⁺ channels open, potassium rushes out, and the voltage falls back toward rest. <b>Hyperpolarization</b>: potassium channels close slowly, so the potential briefly overshoots below −70 mV. Then the Na⁺/K⁺ pump restores the resting gradients. The whole event takes about a millisecond. During the <b>absolute refractory period</b> the neuron cannot fire again no matter the stimulus, which guarantees the impulse travels one direction and limits how fast a neuron can fire."},
   {h:"Propagation",p:"An action potential at one spot depolarizes the membrane just ahead, triggering an action potential there, and so on down the axon — a self-regenerating wave that does not fade with distance. In myelinated axons it jumps between nodes of Ranvier (saltatory conduction) far faster than it can creep along bare membrane. Larger-diameter axons also conduct faster. Pain fibers are small and thinly myelinated, which is why a sharp pain arrives after the touch that caused it."}
  ],
  terms:[["Resting membrane potential","About −70 mV, inside negative."],["Threshold","About −55 mV; the voltage that triggers an action potential."],["All-or-none","Fires fully or not at all; intensity is coded by frequency."],["Depolarization / repolarization","Na⁺ in / K⁺ out."],["Refractory period","The interval when a neuron cannot (or can barely) fire again."]],
  clinical:"Local anesthetics like lidocaine block voltage-gated sodium channels — no depolarization, no action potential, no pain signal. Potassium disorders act on the resting potential: hyperkalemia makes cells depolarize more easily and then fail to repolarize, which is why a high K⁺ shows up as peaked T waves and can arrest the heart. Every antiarrhythmic and antiseizure drug is a channel drug; this lesson is their mechanism."},
 {id:"5-3",title:"Synapses and neurotransmitters — where drugs act",mins:7,dia:null,
  cards:["m5-13","m5-14"],
  sections:[
   {h:"Crossing the gap",p:"Neurons do not touch. At a <b>synapse</b>, an action potential arriving at the axon terminal opens voltage-gated calcium channels; calcium triggers vesicles to fuse with the membrane and release <b>neurotransmitter</b> into the <b>synaptic cleft</b>. The transmitter diffuses across, binds receptors on the postsynaptic cell, and opens ion channels there — an <b>excitatory</b> transmitter depolarizes the next cell toward threshold; an <b>inhibitory</b> one hyperpolarizes it away. The signal is then ended by enzymes that break the transmitter down, by reuptake pumps that pull it back into the terminal, or by diffusion away."},
   {h:"Summation: the neuron as a calculator",p:"A single neuron receives thousands of synapses. Its cell body adds them up: excitatory inputs push toward threshold, inhibitory inputs pull away, and only if the sum at the axon hillock crosses threshold does it fire. Inputs summed over time from one synapse (temporal) or across many synapses at once (spatial) both count. This integration is the basic computation of the nervous system."},
   {h:"The transmitters you will meet constantly",p:"<b>Acetylcholine (ACh)</b> drives skeletal muscle at the neuromuscular junction and is the main parasympathetic transmitter. <b>Norepinephrine</b> is the sympathetic transmitter at most target organs and modulates arousal and attention. <b>Dopamine</b> underlies reward and voluntary movement — its loss in the substantia nigra causes Parkinson's disease. <b>Serotonin</b> shapes mood, sleep, and appetite. <b>Glutamate</b> is the brain's main excitatory transmitter; <b>GABA</b> is the main inhibitory one — and nearly every sedative, from benzodiazepines to alcohol, works by boosting GABA. <b>Endorphins</b> are the body's own opioids."}
  ],
  terms:[["Synaptic cleft","The gap between a terminal and the next cell."],["Excitatory / inhibitory","Pushes the next cell toward / away from threshold."],["Reuptake","Pumping transmitter back into the terminal to end the signal."],["GABA","The brain's main inhibitory transmitter."],["Glutamate","The brain's main excitatory transmitter."]],
  clinical:"This lesson is pharmacology's front door. SSRIs block serotonin reuptake. Benzodiazepines enhance GABA. Opioids bind endorphin receptors. Levodopa replaces dopamine. Anticholinesterase drugs (for myasthenia gravis) prolong ACh. Antipsychotics block dopamine receptors. When you learn a psychiatric or neurological drug, ask which transmitter and which step — release, receptor, breakdown, or reuptake — it touches."},
 {id:"5-4",title:"The brain and spinal cord — a working map",mins:11,dia:"brain",
  cards:["m5-15","m5-16","m5-17","m5-18","m5-19","m5-20","m5-21","m5-24","m5-26","m5-27","d-brain-frontal","d-brain-parietal","d-brain-temporal","d-brain-occipital","d-brain-cerebellum","d-brain-brainstem"],
  sections:[
   {h:"The cerebrum and its lobes",p:"The <b>cerebrum</b> is the large, folded upper brain; its outer gray matter is the <b>cerebral cortex</b>, and its folds (gyri) and grooves (sulci) multiply the surface area for processing. Each hemisphere has four lobes. The <b>frontal lobe</b> handles voluntary movement (from the precentral gyrus), speech production, planning, judgment, and personality. The <b>parietal lobe</b> processes touch, pressure, temperature, and pain (postcentral gyrus) and builds spatial awareness. The <b>temporal lobe</b> handles hearing, language comprehension, and memory. The <b>occipital lobe</b> is vision. The two hemispheres communicate through the corpus callosum, and each mostly controls the <i>opposite</i> side of the body."},
   {h:"Beneath the cortex",p:"The <b>thalamus</b> is the relay station — nearly all sensory input passes through it on the way to the cortex. Just below, the <b>hypothalamus</b> is the master of homeostasis: temperature, hunger, thirst, sleep, and the link to the endocrine system through the pituitary gland. The <b>basal nuclei</b> smooth and coordinate movement; their dopamine-dependent circuits are what fail in Parkinson's. The limbic system, including the hippocampus and amygdala, handles memory formation and emotion."},
   {h:"Brainstem and cerebellum",p:"The <b>brainstem</b> — <b>midbrain, pons, and medulla oblongata</b> — connects brain to spinal cord and contains the centers that keep you alive: the medulla regulates heart rate, blood pressure, and breathing, and hosts the vomiting and swallowing reflexes. Ten of the twelve cranial nerves emerge here. Damage to the brainstem is so often fatal that brain death is defined largely by the loss of its reflexes. The <b>cerebellum</b> sits behind it and coordinates balance, posture, and the smooth timing of voluntary movement; a person with cerebellar damage can move but cannot move precisely."},
   {h:"Protection: meninges, CSF, and the blood–brain barrier",p:"Three membranes wrap the CNS: the tough outer <b>dura mater</b>, the web-like <b>arachnoid mater</b>, and the delicate <b>pia mater</b> clinging to the surface. <b>Cerebrospinal fluid (CSF)</b> circulates in the subarachnoid space and the ventricles, cushioning the brain, floating it to reduce its effective weight, and carrying nutrients and waste. The <b>blood–brain barrier</b> — tight junctions between brain capillary cells — blocks most substances in the blood from reaching brain tissue, protecting it from toxins but also blocking many drugs and antibiotics."},
   {h:"The spinal cord and reflexes",p:"The spinal cord carries ascending sensory tracts and descending motor tracts, and it ends around L1–L2, with nerve roots continuing below as the cauda equina. It gives off <b>31 pairs of spinal nerves</b>; the brain gives off <b>12 pairs of cranial nerves</b>. The cord also handles <b>reflexes</b> on its own: in a reflex arc, a receptor fires a sensory neuron, which synapses in the cord directly (or through one interneuron) onto a motor neuron, which fires the effector — all before the brain knows. Bypassing the brain is the point; it is why you pull your hand from a hot stove before you feel the burn."}
  ],
  terms:[["Frontal / parietal / temporal / occipital","Movement & judgment / touch & space / hearing & memory / vision."],["Thalamus","Sensory relay station to the cortex."],["Hypothalamus","Homeostasis center; links nervous and endocrine systems."],["Medulla oblongata","Brainstem center for heart rate, breathing, blood pressure."],["Reflex arc","Receptor → sensory neuron → cord → motor neuron → effector."]],
  clinical:"Stroke assessment is this map. A left middle cerebral artery stroke hits the frontal and temporal lobes: right-sided weakness and, because language sits on the left in most people, aphasia. An occipital stroke causes vision loss with normal strength. A cerebellar stroke causes ataxia and vertigo. Rising intracranial pressure pushes the brainstem downward and is a life-threatening emergency, which is why a change in level of consciousness, pupils, or breathing pattern is the finding you report first."},
 {id:"5-5",title:"The autonomic nervous system — fight-or-flight versus rest-and-digest",mins:7,dia:null,
  cards:["m5-22","m5-23"],
  sections:[
   {h:"Two divisions, most organs get both",p:"The autonomic nervous system runs the body's involuntary machinery — heart rate, blood vessel tone, digestion, pupil size, glands — through two opposing branches. The <b>sympathetic</b> division prepares the body for action: <b>fight or flight</b>. The <b>parasympathetic</b> division conserves and restores: <b>rest and digest</b>. Nearly every organ receives fibers from both, and its current state is the balance between them. Each pathway uses two neurons: a preganglionic neuron from the CNS synapses in a ganglion onto a postganglionic neuron that reaches the organ."},
   {h:"Sympathetic activation",p:"Sympathetic output raises heart rate and the force of contraction, dilates the airways, dilates the pupils, shunts blood from skin and gut to skeletal muscle, releases glucose from the liver, slows digestion, and triggers sweating. The adrenal medulla amplifies all of this by dumping epinephrine and norepinephrine into the blood. At most target organs the sympathetic transmitter is <b>norepinephrine</b>, acting on alpha and beta adrenergic receptors — which is why drugs named for those receptors (beta-blockers, alpha-agonists) do what they do."},
   {h:"Parasympathetic activation",p:"Parasympathetic output, carried largely by the <b>vagus nerve</b>, slows the heart, constricts the pupils and airways, and stimulates digestion, salivation, and elimination. Its transmitter at target organs is <b>acetylcholine</b> acting on muscarinic receptors, so anticholinergic drugs produce the opposite picture — dry mouth, fast heart, dilated pupils, constipation, urinary retention. A useful memory hook: stimulating the vagus (bearing down, carotid massage) can slow a racing heart."}
  ],
  terms:[["Sympathetic","Fight or flight; norepinephrine at targets."],["Parasympathetic","Rest and digest; acetylcholine at targets."],["Vagus nerve","Main parasympathetic nerve to heart and gut."],["Adrenergic receptors","Alpha and beta receptors for norepinephrine/epinephrine."],["Muscarinic receptors","ACh receptors on parasympathetic target organs."]],
  clinical:"Read a patient's vitals as autonomic tone. Tachycardia, dilated pupils, pale cool skin, and sweating is sympathetic surge — pain, fear, blood loss, or hypoglycemia. A drug's side-effect list is usually just the autonomic receptors it touches: beta-blockers slow the heart and can tighten airways in asthmatics; atropine blocks ACh and is given to speed a dangerously slow heart."}
];
LESSONS[6]=[
 {id:"6-1",title:"How hormones work — receptors, feedback, and the hypothalamus–pituitary axis",mins:9,dia:"endocrine",
  cards:["m6-1","m6-2","m6-3","m6-4","m6-5","m6-6","m6-7","m6-15","d-endocrine-hypo","d-endocrine-pit","d-endocrine-thy","d-endocrine-fb"],
  sections:[
   {h:"Slow, broad, and lasting",p:"The nervous system sends fast, targeted, short-lived signals along wires. The endocrine system sends <b>hormones</b> — chemical messengers released by ductless <b>endocrine glands</b> into the blood — that reach every cell in the body, act more slowly, and keep acting for minutes to days. (<b>Exocrine</b> glands, by contrast, secrete through ducts onto a surface: sweat, saliva, digestive enzymes.) A hormone floods the whole body but affects only cells that carry its <b>receptor</b>; that is how one signal produces a specific effect. Water-soluble hormones (most peptides, epinephrine) bind receptors on the cell surface and trigger second messengers inside. Lipid-soluble hormones (steroids like cortisol, and thyroid hormone) pass through the membrane and switch genes on or off directly, which is why their effects build slowly and last."},
   {h:"The hypothalamus rules the pituitary",p:"The <b>pituitary gland</b> was called the master gland because its hormones control so many others — but it is itself controlled by the <b>hypothalamus</b>, the brain region that links the nervous and endocrine systems. The hypothalamus sends releasing and inhibiting hormones through a private set of vessels to the <b>anterior pituitary</b>, which then releases growth hormone (GH), thyroid-stimulating hormone (TSH), adrenocorticotropic hormone (ACTH), follicle-stimulating and luteinizing hormones (FSH, LH), and prolactin. The <b>posterior pituitary</b> does not make hormones at all: it stores and releases two made in the hypothalamus — <b>antidiuretic hormone (ADH)</b>, which tells the kidneys to reabsorb water, and <b>oxytocin</b>, which drives labor contractions and milk let-down."},
   {h:"Negative feedback, hormone edition",p:"Endocrine axes regulate themselves by negative feedback. Take the thyroid: low thyroid hormone prompts the hypothalamus to release TRH; TRH makes the anterior pituitary release TSH; TSH makes the thyroid release T3 and T4; and rising T3/T4 then <i>inhibit</i> both TRH and TSH, shutting the axis down. The same pattern governs cortisol (CRH → ACTH → cortisol) and the sex hormones. Once you can trace the loop, most endocrine disorders explain themselves: a failing thyroid gland means low T4 and a <i>high</i> TSH, because the pituitary keeps shouting at a gland that cannot answer."},
   {h:"Reading the loop diagnostically",p:"Because of feedback, the level of the controlling hormone tells you where a problem lives. High TSH with low T4 is primary hypothyroidism (the gland). Low TSH with low T4 points upstream to the pituitary. Low TSH with high T4 is hyperthyroidism — the gland is overproducing and the pituitary has backed off. This logic is the same one used for cortisol and ACTH, and it is why a lab report lists both hormones side by side."}
  ],
  terms:[["Endocrine vs. exocrine","Ductless, into blood / through ducts onto a surface."],["Target cell","A cell that carries the receptor for a given hormone."],["Anterior pituitary","Releases GH, TSH, ACTH, FSH, LH, prolactin under hypothalamic control."],["ADH","Posterior pituitary hormone that makes the kidney retain water."],["TSH","Pituitary hormone driving the thyroid; rises when thyroid hormone falls."]],
  clinical:"Thyroid disease is common and its labs are pure feedback logic. A patient on levothyroxine is dosed to normalize TSH, not just T4, because TSH is the pituitary's honest verdict on whether the body has enough. Diabetes insipidus — not to be confused with diabetes mellitus — is ADH failure: the kidneys cannot hold water, and the patient produces liters of dilute urine."},
 {id:"6-2",title:"The major glands — thyroid, parathyroid, adrenals, and pancreas",mins:10,dia:null,
  cards:["m6-8","m6-9","m6-10","m6-11","m6-12","m6-13","m6-14","m6-16"],
  sections:[
   {h:"Thyroid and parathyroids",p:"The <b>thyroid</b> sits in front of the trachea and makes <b>T3 and T4</b>, which set the body's metabolic rate — heat production, heart rate, energy use, growth. Too much (hyperthyroidism) runs everything fast: weight loss, heat intolerance, tachycardia, anxiety. Too little runs everything slow: weight gain, cold intolerance, fatigue, bradycardia. The thyroid also makes <b>calcitonin</b>, which lowers blood calcium. Embedded on its back are four tiny <b>parathyroid glands</b> that do the opposite: <b>parathyroid hormone (PTH)</b> raises blood calcium by stimulating osteoclasts, increasing kidney reabsorption, and activating vitamin D. PTH is the dominant calcium regulator; calcitonin is minor."},
   {h:"The adrenal glands",p:"Each adrenal gland caps a kidney and is really two organs. The outer <b>adrenal cortex</b> makes steroids: <b>aldosterone</b>, which tells the kidney to retain sodium (and with it, water) and excrete potassium, raising blood volume and pressure; <b>cortisol</b>, the long-term stress hormone, which raises blood glucose, breaks down protein and fat for fuel, and suppresses inflammation and immunity; and small amounts of sex hormones. The inner <b>adrenal medulla</b> is essentially a sympathetic ganglion that releases <b>epinephrine and norepinephrine</b> into the blood for the rapid fight-or-flight surge."},
   {h:"The pancreas and blood glucose",p:"The pancreas is both exocrine (digestive enzymes) and endocrine (islets of Langerhans). In the islets, <b>beta cells</b> release <b>insulin</b> when blood glucose rises after a meal; insulin drives glucose into cells and promotes storage as glycogen and fat, lowering blood glucose. <b>Alpha cells</b> release <b>glucagon</b> when glucose falls; glucagon makes the liver release stored glucose, raising it. The two hormones oppose each other minute to minute and hold blood glucose in a range of roughly 70–100 mg/dL fasting."},
   {h:"Diabetes mellitus, mechanistically",p:"<b>Type 1 diabetes</b> is the autoimmune destruction of beta cells: no insulin is made, so glucose cannot enter cells and piles up in the blood while cells starve and burn fat instead, producing ketones — the basis of diabetic ketoacidosis. <b>Type 2 diabetes</b> begins as <b>insulin resistance</b>: insulin is present but target cells respond poorly, the pancreas overworks to compensate, and eventually beta cells fail. In both, chronically high glucose damages blood vessels and nerves, which is why the complications are heart disease, kidney failure, blindness, and neuropathy."}
  ],
  terms:[["T3 / T4","Thyroid hormones that set metabolic rate."],["PTH","Parathyroid hormone; the main raiser of blood calcium."],["Aldosterone","Adrenal cortex hormone: retain Na⁺ and water, excrete K⁺."],["Cortisol","Long-term stress hormone; raises glucose, suppresses inflammation."],["Insulin / glucagon","Lower / raise blood glucose."]],
  clinical:"Hypoglycemia is a nursing emergency you can reason through: a diabetic patient who took insulin and skipped a meal becomes shaky, sweaty, confused, and tachycardic — the sympathetic surge and the glucose-starved brain. The fix is glucose, fast. Long-term steroid therapy mimics excess cortisol (weight gain, high glucose, thin skin, infection risk) and, because it suppresses the body's own axis, can never be stopped abruptly."}
];
LESSONS[7]=[
 {id:"7-1",title:"Blood — what it carries and how it clots",mins:8,dia:null,
  cards:["m7-1","m7-2","m7-3","m7-4","m7-5","m7-6","m7-7"],
  sections:[
   {h:"A connective tissue that flows",p:"Blood is connective tissue whose matrix is liquid: <b>plasma</b>, about 90% water, carries proteins (albumin for osmotic pressure, antibodies, clotting factors), nutrients, hormones, gases, wastes, and electrolytes. Suspended in it are the <b>formed elements</b>: <b>erythrocytes</b> (red blood cells) that carry oxygen, <b>leukocytes</b> (white blood cells) that defend, and <b>platelets</b> that clot. The fraction of blood volume made up of red cells is the <b>hematocrit</b> — roughly 45% in men and 40% in women. An adult carries about five liters."},
   {h:"Red cells and hemoglobin",p:"Red blood cells are biconcave discs with no nucleus, which maximizes room for <b>hemoglobin</b> — the iron-containing protein that binds oxygen in the lungs and releases it in the tissues. Each hemoglobin molecule carries four oxygen molecules; a single red cell holds about 250 million of them. Red cells are made in red bone marrow under the direction of <b>erythropoietin</b>, a hormone the kidneys release when oxygen is low, and they live about 120 days before the spleen and liver recycle them. Too few red cells or too little hemoglobin is <b>anemia</b>: oxygen delivery falls no matter how well the lungs work."},
   {h:"White cells and platelets",p:"Leukocytes are the mobile immune system. Neutrophils are the most numerous and the first responders to bacterial infection; lymphocytes (B and T cells) run adaptive immunity; monocytes become tissue macrophages; eosinophils and basophils handle parasites and allergy. A rising neutrophil count signals infection; a falling one signals a bone marrow under attack. <b>Platelets</b> are cell fragments that patrol for damaged vessels."},
   {h:"Hemostasis: stopping the bleeding",p:"When a vessel is cut, hemostasis proceeds in three steps. <b>Vascular spasm</b>: the vessel constricts to slow flow. <b>Platelet plug</b>: platelets stick to the exposed collagen and to each other, releasing chemicals that recruit more — a positive feedback loop. <b>Coagulation</b>: a cascade of clotting factors, most made in the liver and several dependent on vitamin K, converts fibrinogen into <b>fibrin</b> threads that mesh the plug into a solid clot. Later, the clot is dissolved by plasmin. Blood types matter here too: the A and B antigens on red cells, plus the Rh factor, determine compatibility — <b>O negative</b> lacks all three and is the universal donor; <b>AB positive</b> has all three and is the universal recipient."}
  ],
  terms:[["Plasma","The liquid matrix of blood."],["Hematocrit","Percentage of blood volume that is red cells."],["Hemoglobin","Iron-containing oxygen carrier in red cells."],["Erythropoietin","Kidney hormone that stimulates red cell production."],["Fibrin","Protein threads that form the clot."]],
  clinical:"A complete blood count is this lesson in numbers: hemoglobin and hematocrit for oxygen-carrying capacity, white count and differential for infection or marrow disease, platelets for bleeding risk. Anticoagulants target the cascade — warfarin blocks vitamin K, heparin amplifies a natural inhibitor — which is why INR and aPTT are monitored, and why a patient on them bruises and bleeds."},
 {id:"7-2",title:"The heart — chambers, valves, the conduction system, and the cardiac cycle",mins:12,dia:"heart",
  cards:["m7-8","m7-9","m7-10","m7-11","m7-12","m7-13","m7-14","m7-15","m7-16","m7-21","d-heart-ra","d-heart-rv","d-heart-la","d-heart-lv","d-heart-tri","d-heart-mit","d-heart-ao","d-heart-pa"],
  sections:[
   {h:"Four chambers, two pumps",p:"The heart is two pumps side by side. The right side receives deoxygenated blood from the body and sends it to the lungs — the <b>pulmonary circuit</b>. The left side receives oxygenated blood from the lungs and sends it to the whole body — the <b>systemic circuit</b>. Each side has a receiving chamber, the <b>atrium</b>, and a pumping chamber, the <b>ventricle</b>. The <b>left ventricle</b> has by far the thickest wall because it must generate enough pressure to push blood through the entire body, while the right ventricle only reaches the nearby lungs. A muscular wall, the <b>septum</b>, separates the two sides so the two blood supplies never mix."},
   {h:"The path of blood — memorize it cold",p:"Deoxygenated blood enters the <b>right atrium</b> from the superior and inferior vena cavae → passes through the <b>tricuspid valve</b> → into the <b>right ventricle</b> → out through the <b>pulmonary valve</b> into the <b>pulmonary trunk</b> and arteries → to the lungs, where it picks up oxygen → returns through four pulmonary veins into the <b>left atrium</b> → through the <b>mitral (bicuspid) valve</b> → into the <b>left ventricle</b> → out through the <b>aortic valve</b> into the <b>aorta</b> → to the body. The two atrioventricular valves (tricuspid, mitral) are tethered by <b>chordae tendineae</b> to <b>papillary muscles</b> that keep them from blowing backward under ventricular pressure. The heart muscle itself is fed not from inside the chambers but by the <b>coronary arteries</b> branching off the aorta — the arteries whose blockage causes a heart attack."},
   {h:"The heart's own pacemaker",p:"Cardiac muscle contracts on its own, driven by a built-in conduction system. The <b>sinoatrial (SA) node</b> in the right atrium depolarizes spontaneously fastest of all, so it sets the pace — about 60–100 beats per minute. Its impulse spreads across both atria (they contract), then reaches the <b>atrioventricular (AV) node</b>, which <i>delays</i> it for about a tenth of a second so the ventricles can finish filling. The impulse then races down the <b>bundle of His</b>, the right and left <b>bundle branches</b>, and the <b>Purkinje fibers</b>, so the ventricles contract as a unit from the apex upward. The ECG records exactly this sequence: the P wave is atrial depolarization, the QRS complex is ventricular depolarization, and the T wave is ventricular repolarization."},
   {h:"The cardiac cycle and cardiac output",p:"One heartbeat is one cardiac cycle: <b>diastole</b>, when the chambers relax and fill, and <b>systole</b>, when they contract and eject. The \"lub\" of a heartbeat is the AV valves snapping shut as ventricular systole begins; the \"dub\" is the semilunar valves closing as it ends. The volume of blood one ventricle pumps per minute is <b>cardiac output</b> = <b>heart rate × stroke volume</b>, about 5 liters at rest. Stroke volume rises when the ventricle fills more (preload), contracts harder (contractility), or pushes against less resistance (afterload). The autonomic nervous system tunes rate and contractility beat to beat: sympathetic input speeds and strengthens, parasympathetic (vagal) input slows."}
  ],
  terms:[["Tricuspid / mitral","Right / left atrioventricular valves."],["SA node","The pacemaker in the right atrium."],["AV node","Delays the impulse so the ventricles fill first."],["Systole / diastole","Contraction / relaxation and filling."],["Cardiac output","Heart rate × stroke volume, ~5 L/min at rest."]],
  clinical:"Heart failure is cardiac output that cannot meet demand. Left-sided failure backs blood up into the lungs — crackles, shortness of breath, pink frothy sputum. Right-sided failure backs blood up into the body — swollen legs, distended neck veins, an enlarged liver. A blocked coronary artery starves the muscle it feeds, and the ECG shows which wall by which leads change. Every rhythm you will ever read on a monitor is the conduction system in this lesson, working or failing."},
 {id:"7-3",title:"Vessels and blood pressure — how flow is delivered and controlled",mins:8,dia:null,
  cards:["m7-17","m7-18","m7-19","m7-20"],
  sections:[
   {h:"Arteries, capillaries, veins",p:"<b>Arteries</b> carry blood away from the heart under high pressure; their walls are thick, muscular, and elastic, stretching with each beat and recoiling to keep blood moving between beats. They branch into arterioles, whose smooth muscle is the main adjustable resistance in the system. Arterioles feed <b>capillaries</b> — vessels one endothelial cell thick, where all exchange of gases, nutrients, and wastes happens across their walls. Capillaries drain into venules and then <b>veins</b>, which return blood to the heart under low pressure; their walls are thin, they hold most of the body's blood volume at any moment, and they contain <b>valves</b> to prevent backflow, relying on skeletal muscle contraction and breathing to push blood upward against gravity."},
   {h:"What blood pressure means",p:"Blood pressure is the force blood exerts on arterial walls, reported as <b>systolic</b> (during ventricular contraction) over <b>diastolic</b> (during relaxation), normally around 120/80 mmHg. It is the product of <b>cardiac output</b> and <b>peripheral resistance</b> — how hard it is to push blood through the arterioles. Widen the arterioles and pressure falls; constrict them and it rises. Blood volume matters too: lose a liter of blood and pressure drops; retain salt and water and it climbs. Pressure falls steadily from the aorta (about 100 mmHg mean) to the capillaries (about 30) to the vena cavae (near zero), which is the gradient that drives flow."},
   {h:"Regulating pressure",p:"Short-term control is neural: <b>baroreceptors</b> in the carotid sinus and aortic arch sense stretch and report to the medulla, which adjusts heart rate and arteriolar tone within seconds — stand up quickly, pressure dips, and the reflex restores it before you faint. Long-term control is renal and hormonal: the kidneys adjust blood volume through the renin–angiotensin–aldosterone system and ADH, both covered in Module 8. Hypertension develops when these systems settle at a set point that is too high, quietly damaging arteries, heart, kidneys, and retina for years."},
   {h:"Capillary exchange",p:"At the arterial end of a capillary, blood pressure pushes fluid out into the tissues; at the venous end, the osmotic pull of plasma proteins (mainly albumin) draws most of it back. The small excess that stays in the tissue is collected by the lymphatic system. Upset that balance — high venous pressure in heart failure, low albumin in liver disease or malnutrition, leaky capillaries in inflammation — and fluid accumulates in the tissues as <b>edema</b>."}
  ],
  terms:[["Arteriole","Small artery whose smooth muscle sets peripheral resistance."],["Capillary","Single-cell-thick exchange vessel."],["Systolic / diastolic pressure","Pressure during ventricular contraction / relaxation."],["Baroreceptor","Pressure sensor in the carotid sinus and aortic arch."],["Edema","Excess fluid in the tissues."]],
  clinical:"Shock is blood pressure failing to perfuse organs, and its types map onto this lesson: hypovolemic (too little volume), cardiogenic (the pump fails), distributive (arterioles dilate massively, as in sepsis and anaphylaxis). Orthostatic hypotension is a baroreceptor reflex too slow for the patient who just stood up — a fall risk you assess by checking lying and standing pressures. Antihypertensives act on each lever: diuretics on volume, beta-blockers on cardiac output, vasodilators and ACE inhibitors on resistance."},
 {id:"7-4",title:"Lymphatics and immunity — drainage, defense, and memory",mins:8,dia:null,
  cards:["m7-22","m7-23","m7-24","m7-25","m7-26"],
  sections:[
   {h:"The lymphatic system returns the leak",p:"Capillaries leak a few liters of fluid into the tissues every day. The <b>lymphatic system</b> collects that fluid — now called lymph — in blind-ended lymphatic capillaries, filters it through <b>lymph nodes</b> packed with immune cells, and returns it to the bloodstream near the heart. It also absorbs dietary fat from the intestine and houses the lymphoid organs: the thymus (where T cells mature), the spleen (which filters blood and recycles red cells), and the tonsils. Swollen, tender lymph nodes are the nodes doing their job against an infection upstream."},
   {h:"Innate immunity: fast and general",p:"<b>Innate immunity</b> is present from birth and responds the same way to any invader. The first line is barriers — skin, mucous membranes, stomach acid. The second line is <b>inflammation</b>: damaged tissue releases histamine and other signals that dilate vessels and make them leaky, bringing plasma proteins and phagocytes to the site. The cardinal signs — redness, heat, swelling, pain, and loss of function — are the vessels dilating and the fluid arriving. Neutrophils and macrophages phagocytose invaders; natural killer cells destroy infected and cancerous cells; complement proteins and interferons amplify the response; fever raises body temperature to hinder pathogens."},
   {h:"Adaptive immunity: specific and remembered",p:"<b>Adaptive immunity</b> targets a specific invader and remembers it. An <b>antigen</b> is any molecule the immune system recognizes as foreign. <b>B lymphocytes</b> provide humoral immunity: when activated, they become plasma cells that mass-produce <b>antibodies</b>, proteins that bind that specific antigen and mark it for destruction. <b>T lymphocytes</b> provide cell-mediated immunity: helper T cells coordinate the whole response (they are what HIV destroys), and cytotoxic T cells directly kill infected cells. Both leave behind <b>memory cells</b>, so the second exposure to the same antigen produces a faster, stronger response — which is the entire principle of vaccination."}
  ],
  terms:[["Lymph node","Filter station packed with lymphocytes."],["Inflammation","Innate response: dilation, leakiness, phagocyte recruitment."],["Antigen","A molecule the immune system recognizes as foreign."],["B cell / antibody","Humoral immunity; antibodies bind specific antigens."],["Helper T cell","Coordinates the adaptive response; destroyed by HIV."]],
  clinical:"Sepsis is inflammation that has gone systemic — vessels dilate and leak everywhere, pressure collapses, and organs fail; it is why a fever with a fast heart and dropping pressure is treated as an emergency. Allergy is adaptive immunity misfiring at a harmless antigen, and anaphylaxis is that response at full volume. Immunosuppressed patients — chemotherapy, transplant drugs, HIV — lose the defenses in this lesson, which is why every infection-control precaution exists."}
];
LESSONS[8]=[
 {id:"8-1",title:"Breathing — the airway, the alveoli, and how gases move",mins:10,dia:"resptree",
  cards:["m8-1","m8-2","m8-3","m8-4","m8-5","m8-6","m8-7","m8-8","d-resptree-pharynx","d-resptree-larynx","d-resptree-trachea","d-resptree-bronchi","d-resptree-bronchiole","d-resptree-alveoli","d-resptree-diaphragm","d-alveolus-alv","d-alveolus-cap","d-alveolus-memb","d-alveolus-o2","d-alveolus-co2"],
  sections:[
   {h:"The airway, top to bottom",p:"Air enters through the <b>nasal cavity</b>, where it is warmed, moistened, and filtered, passes the <b>pharynx</b> (throat), then the <b>larynx</b> — the voice box, guarded by the <b>epiglottis</b>, which flips down during swallowing to keep food out of the airway. Below it the <b>trachea</b> descends, held open by C-shaped cartilage rings, and splits into a right and left <b>primary bronchus</b>, one per lung. Inside the lungs the bronchi branch again and again into smaller bronchi and then <b>bronchioles</b>, whose walls contain smooth muscle rather than cartilage — which is why they can constrict in asthma. Everything down to the terminal bronchioles is the conducting zone: plumbing that carries air but exchanges no gas."},
   {h:"Alveoli: where the exchange happens",p:"The bronchioles end in clusters of tiny air sacs called <b>alveoli</b> — about 300 million of them, with a combined surface area the size of a tennis court. Each alveolus is wrapped in capillaries, and the <b>respiratory membrane</b> between air and blood is a fraction of a micrometer thick: one alveolar cell, one capillary cell, and their fused basement membranes. Oxygen diffuses across it into the blood and carbon dioxide diffuses out, driven purely by concentration gradients. A thin coating of <b>surfactant</b> lowers surface tension so the alveoli do not collapse on exhalation; premature infants who lack it develop respiratory distress syndrome."},
   {h:"The mechanics of breathing",p:"Breathing is a pressure game. To inhale, the <b>diaphragm</b> contracts and flattens and the external intercostals lift the ribs, enlarging the thoracic cavity; pressure inside the lungs drops below atmospheric pressure and air flows in. Quiet exhalation is passive — the diaphragm relaxes, the elastic lungs and chest wall recoil, pressure rises, and air flows out. Forced exhalation adds the abdominal and internal intercostal muscles. A pneumothorax breaks this system: air leaks into the pleural space, the lung can no longer be pulled open, and it collapses."},
   {h:"Gas transport and the control of breathing",p:"Oxygen travels almost entirely bound to <b>hemoglobin</b>; only a little dissolves in plasma. Carbon dioxide travels mostly as <b>bicarbonate</b> ions in the plasma (about 70%), some bound to hemoglobin, some dissolved. That bicarbonate conversion means CO₂ and blood pH are tied together — more CO₂, more acid. The respiratory center in the <b>medulla</b> sets the rhythm, and its main driver is not oxygen: it is rising CO₂ (sensed as falling pH by central chemoreceptors), which is why holding your breath becomes unbearable long before your oxygen runs low. Oxygen only takes over as the drive when it falls very low, which is a concern in patients with chronic lung disease."}
  ],
  terms:[["Epiglottis","Flap that seals the larynx during swallowing."],["Bronchiole","Small airway with smooth muscle, no cartilage."],["Respiratory membrane","The paper-thin barrier between alveolar air and blood."],["Surfactant","Reduces alveolar surface tension, preventing collapse."],["Central chemoreceptors","Sense rising CO₂ (as falling pH) and drive breathing."]],
  clinical:"Respiratory assessment is this anatomy heard through a stethoscope: wheezes are narrowed bronchioles, crackles are fluid in alveoli, absent sounds are a collapsed or blocked lung. Pulse oximetry reads hemoglobin saturation. In COPD, chronically high CO₂ can blunt the central drive, so giving too much oxygen can suppress breathing — one of the few times oxygen must be titrated carefully."},
 {id:"8-2",title:"The kidney and the nephron — filter everything, then take back what you need",mins:11,dia:"nephron",
  cards:["m8-9","m8-10","m8-11","m8-12","m8-13","m8-14","m8-15","m8-16","d-nephron-glom","d-nephron-bow","d-nephron-pct","d-nephron-loop","d-nephron-dct","d-nephron-cd"],
  sections:[
   {h:"What the kidneys actually do",p:"The kidneys make urine, but that is the least of it. They regulate blood volume and pressure, the concentration of every major electrolyte, and acid–base balance; they release <b>erythropoietin</b> to drive red cell production and <b>renin</b> to raise blood pressure; and they activate vitamin D. Each kidney holds about a million <b>nephrons</b>, and each nephron processes blood the same way: <b>filter</b> almost everything small out of the blood, then <b>reabsorb</b> what the body needs and <b>secrete</b> a little extra waste into what remains. The final product — about 1.5 liters a day out of 180 liters filtered — travels through the ureters to the bladder and out the urethra."},
   {h:"The renal corpuscle: filtration",p:"Blood arrives at each nephron through an afferent arteriole and enters the <b>glomerulus</b>, a tuft of leaky capillaries under high pressure. That pressure forces water and small solutes — glucose, amino acids, ions, urea — out of the blood and into the surrounding cup, the <b>glomerular (Bowman's) capsule</b>. Blood cells and large proteins are too big to pass and stay in the blood, leaving through the efferent arteriole. The fluid in the capsule is now <b>filtrate</b>, and the rate it forms — the <b>glomerular filtration rate (GFR)</b>, about 125 mL/min — is the single best measure of kidney function."},
   {h:"The tubule: reabsorption and secretion",p:"Filtrate then flows through the tubule, and the nephron takes back what it wants. The <b>proximal convoluted tubule</b> does the heavy lifting: it reabsorbs about 65% of the water and sodium and essentially all of the glucose and amino acids. The <b>loop of Henle</b> dips into the salty medulla and back, building the concentration gradient that will let the kidney concentrate urine. The <b>distal convoluted tubule</b> fine-tunes sodium, potassium, calcium, and pH under hormonal control — this is where <b>aldosterone</b> acts, retaining sodium and dumping potassium. The <b>collecting duct</b> makes the final water decision: <b>ADH</b> inserts water channels so water is reabsorbed and urine is concentrated; without ADH, water stays in the tubule and urine is dilute. Along the way, the tubule also <b>secretes</b> hydrogen ions, potassium, and some drugs into the filtrate for excretion."},
   {h:"RAAS: how the kidney raises blood pressure",p:"When blood pressure or sodium delivery to the kidney falls, the kidney releases <b>renin</b>. Renin converts angiotensinogen to angiotensin I; angiotensin-converting enzyme (ACE) in the lungs converts that to <b>angiotensin II</b>, a powerful vasoconstrictor that also triggers <b>aldosterone</b> release from the adrenal cortex. Aldosterone retains sodium, water follows, blood volume rises, and pressure is restored. This <b>renin–angiotensin–aldosterone system</b> is the body's main long-term pressure regulator — and the target of ACE inhibitors, ARBs, and aldosterone blockers, three of the most prescribed drug classes in medicine."}
  ],
  terms:[["Nephron","The functional unit of the kidney."],["Glomerulus","Capillary tuft where filtration occurs."],["GFR","Glomerular filtration rate; the key measure of kidney function."],["Aldosterone","Retains Na⁺ (and water), excretes K⁺ at the distal tubule."],["ADH","Opens water channels in the collecting duct; concentrates urine."]],
  clinical:"Kidney labs are this lesson: creatinine and BUN rise when GFR falls, and estimated GFR stages chronic kidney disease. Urine output is the bedside version — less than 30 mL/hour means the kidneys are not being perfused. Diuretics each target a tubule segment: loop diuretics (furosemide) hit the loop of Henle and are the most powerful; thiazides hit the distal tubule; spironolactone blocks aldosterone and, unlike the others, spares potassium."},
 {id:"8-3",title:"Fluids, electrolytes, and acid–base — the hardest topic, made systematic",mins:11,dia:null,
  cards:["m8-17","m8-18","m8-19","m8-20","m8-21","m8-22","m8-23","m8-24","m8-32"],
  sections:[
   {h:"Where the water is",p:"About 60% of an adult's body weight is water, split into two compartments: roughly two-thirds is <b>intracellular fluid</b> inside cells, and one-third is <b>extracellular fluid</b> — the plasma in the vessels plus the interstitial fluid between cells. Water moves freely between compartments by osmosis, following solute. Sodium is the dominant extracellular ion and potassium the dominant intracellular one, which is why a sodium problem shows up as a fluid-volume problem and a potassium problem shows up as a nerve-and-heart problem."},
   {h:"Three lines of pH defense",p:"Blood pH is held between 7.35 and 7.45 by three systems working at three speeds. <b>Chemical buffers</b> — chiefly the bicarbonate system, plus phosphate and proteins — act within seconds, soaking up or releasing hydrogen ions. The <b>respiratory system</b> acts within minutes: CO₂ is effectively an acid (CO₂ + H₂O ⇌ H₂CO₃ ⇌ H⁺ + HCO₃⁻), so breathing faster blows off CO₂ and raises pH, and breathing slower retains CO₂ and lowers it. The <b>kidneys</b> act over hours to days by excreting hydrogen ions and reabsorbing or generating bicarbonate. They are slow but powerful, and they are the only system that can remove fixed acids."},
   {h:"The four primary disorders",p:"Every acid–base disorder is one of four. <b>Respiratory acidosis</b>: CO₂ retained (hypoventilation — COPD, sedative overdose, airway obstruction); pH falls, CO₂ high. <b>Respiratory alkalosis</b>: CO₂ blown off (hyperventilation — anxiety, pain, high altitude); pH rises, CO₂ low. <b>Metabolic acidosis</b>: bicarbonate lost or acid gained (diabetic ketoacidosis, kidney failure, severe diarrhea, lactic acidosis from shock); pH falls, bicarbonate low. <b>Metabolic alkalosis</b>: acid lost or bicarbonate gained (prolonged vomiting, excessive antacids, some diuretics); pH rises, bicarbonate high."},
   {h:"Reading a blood gas in three steps",p:"Step one: look at the <b>pH</b>. Below 7.35 is acidosis, above 7.45 is alkalosis. Step two: find the culprit. If the abnormal value that <i>explains</i> the pH is the <b>CO₂</b> (high with acidosis or low with alkalosis), the problem is respiratory. If it is the <b>bicarbonate</b> (low with acidosis or high with alkalosis), the problem is metabolic. Step three: check for <b>compensation</b> — the other system trying to correct it. In metabolic acidosis the lungs hyperventilate to blow off CO₂ (the deep, rapid Kussmaul breathing of ketoacidosis); in respiratory acidosis the kidneys slowly retain bicarbonate. Compensation moves the pH back toward normal but rarely all the way."}
  ],
  terms:[["Intracellular / extracellular fluid","Inside cells (~2/3) / plasma + interstitial (~1/3)."],["Bicarbonate buffer","HCO₃⁻ / H₂CO₃; the main blood buffer, linked to lungs and kidneys."],["Respiratory acidosis","Low pH from retained CO₂ (hypoventilation)."],["Metabolic acidosis","Low pH from bicarbonate loss or acid gain."],["Compensation","The unaffected system correcting the pH."]],
  clinical:"This is the topic nursing students fear and NCLEX loves. Anchor it to patients: the COPD patient retaining CO₂ (respiratory acidosis), the anxious hyperventilator (respiratory alkalosis), the diabetic in ketoacidosis breathing deep and fast (metabolic acidosis with respiratory compensation), the patient vomiting for two days (metabolic alkalosis). Learn the three-step read and the disorders stop being memorization."},
 {id:"8-4",title:"Digestion and the liver — breaking food down and absorbing it",mins:8,dia:null,
  cards:["m8-25","m8-26","m8-27","m8-28","m8-29","m8-30","m8-31"],
  sections:[
   {h:"The tube and its helpers",p:"The <b>alimentary canal</b> is one continuous tube: mouth → pharynx → esophagus → stomach → small intestine → large intestine → rectum → anus. Food is pushed along by <b>peristalsis</b>, waves of smooth muscle contraction. The <b>accessory organs</b> sit outside the tube and feed secretions into it: the salivary glands (amylase begins starch digestion), the <b>liver</b> (makes bile), the <b>gallbladder</b> (stores and concentrates bile), and the <b>pancreas</b> (delivers the major digestive enzymes plus bicarbonate to neutralize stomach acid). Digestion is mechanical (chewing, churning) and chemical (enzymes breaking large molecules into absorbable small ones)."},
   {h:"Stomach: storage and acid",p:"The stomach stores a meal, churns it into a paste called chyme, and starts protein digestion. Its lining secretes <b>hydrochloric acid</b>, which kills microbes and activates <b>pepsin</b>, the protein-digesting enzyme, and a thick mucus layer that keeps the acid from digesting the stomach itself. Little is absorbed here except water, alcohol, and some drugs. The stomach also makes <b>intrinsic factor</b>, without which vitamin B12 cannot be absorbed downstream — the basis of pernicious anemia."},
   {h:"Small intestine: where absorption actually happens",p:"Nearly all chemical digestion is completed and nearly all <b>absorption</b> occurs in the small intestine — duodenum, jejunum, ileum. Its surface is folded, covered with finger-like <b>villi</b>, and each villus cell carries <b>microvilli</b>, multiplying the absorptive area enormously. Pancreatic enzymes finish breaking carbohydrates, proteins, and fats apart; <b>bile</b> from the liver <b>emulsifies</b> fats into tiny droplets so the fat-digesting enzyme lipase can reach them — bile is a detergent, not an enzyme. Sugars and amino acids are absorbed into the blood and sent straight to the liver; fats are absorbed into lymphatic vessels. The <b>large intestine</b> then reabsorbs water and electrolytes, hosts the gut bacteria that make vitamin K, and forms and stores feces."},
   {h:"The liver: the body's chemical plant",p:"Everything absorbed from the gut passes through the liver first via the hepatic portal vein. The liver <b>detoxifies</b> drugs and alcohol, <b>makes bile</b>, <b>synthesizes plasma proteins</b> — albumin and most clotting factors — <b>stores glycogen</b>, iron, and vitamins, and converts nutrients between forms as the body needs. When it fails, the consequences follow that list: toxins accumulate (confusion), bile backs up (jaundice), albumin falls (edema and ascites), and clotting factors fall (bleeding)."}
  ],
  terms:[["Peristalsis","Waves of smooth-muscle contraction moving contents along the gut."],["Chyme","The acidic paste the stomach produces."],["Villi / microvilli","Folds that multiply the small intestine's absorptive surface."],["Bile","Liver secretion that emulsifies fat; a detergent, not an enzyme."],["Hepatic portal vein","Carries absorbed nutrients from the gut to the liver."]],
  clinical:"Liver function tests, bilirubin, albumin, and INR together describe how much of this lesson's chemical plant still works, and the classic signs of cirrhosis — jaundice, ascites, easy bruising, confusion — are each a specific liver job failing. Nasogastric tubes, tube feeds, and bowel sounds are all about peristalsis. And because the liver metabolizes most drugs, liver disease changes doses of nearly everything you give."}
];
